theme: jekyll-theme-minimal
title: 8 essential skills in python for building physics
description: Applied examples of data interpolaton, integration, equation solving, sensitivity analysis, metamodeling etc.
logo: /img/metamodel.png
show_downloads: False
