theme: jekyll-theme-minimal
title: 7 Methods in Python for Building Physics
description: A selection of tools in python for modelling, building physics etc.
logo: /img/metamodel.png
show_downloads: False
