remote_theme: pages-themes/midnight@v0.2.0
plugins: jekyll-remote-theme
title: 8 essential skills in python for building physics
description: Applied examples of data interpolation, integration, equation solving, sensitivity analysis, metamodeling and parallel computing.
logo: /img/metamodel.png
show_downloads: False
