theme: jekyll-theme-minimal

title: e e
email: x.y@gmail.com
logo: /img/metamodel.png
description: Personal page, who i am as well as some stuff I do and / or like !

show_downloads: False
show_social: True
