theme: jekyll-theme-minimal

title: Edouard WALTHER
email: https://www.researchgate.net/profile/Edouard-Walther
linkedin: https://www.linkedin.com/in/edouard-walther-8b0867a6/
logo: /img/metamodel.png
description: A selection of tools in python for modelling, building physics etc.

show_downloads: False
show_social: True
