theme: jekyll-theme-minimal
title: 8 essential skills in python for building physics
description: A selection of tools in python for modelling, building physics etc.
logo: /img/metamodel.png
show_downloads: False
